#pragma once
#define lest_FEATURE_AUTO_REGISTER 1
#include "PasswordGenerator.h"
#include "lest.hpp"
#include <algorithm>
#include <string>
#include <vector>

#define CASE(name) lest_CASE(specification, name)
static lest::tests specification;

void UniquePassTest(lest::env& lest_env)
{
    PasswordGenerator pgen;
    std::vector<std::string> passwords;
    passwords.reserve(10000);
    for (int a = 0; a < 10000; a++) {
        passwords.push_back(pgen.GeneratePassword());
    }
    std::sort(passwords.begin(), passwords.end());
    bool no_duplicates = std::adjacent_find(passwords.begin(), passwords.end())
            == passwords.end();
    EXPECT(no_duplicates == true);
}

CASE("Generate 10000 passwords and check for uniqueness")
{
    UniquePassTest(lest_env);
}

void CharGenValidTest(lest::env& lest_env)
{
    PasswordGenerator pgen;
    EXPECT(std::isdigit(pgen.GenerateRandomChar(CHAR_TYPE::NUM_CHAR)) == true);
    EXPECT(std::isupper(pgen.GenerateRandomChar(CHAR_TYPE::UP_CHAR)) == true);
    EXPECT(std::islower(pgen.GenerateRandomChar(CHAR_TYPE::LOW_CHAR)) == true);
}

CASE("Check if char types match expected symbol type")
{
    CharGenValidTest(lest_env);
}

void PasswordGenParamsTest(lest::env& lest_env)
{
    PasswordGenerator pgen;
    pgen.SetPasswordLength(15);
    EXPECT(pgen.GeneratePassword().length() == 16); //15 + null terminator
    // Length must be changed by mask
    pgen.SetPasswordMask(std::string("LU-NS"));
    std::string mask_str = pgen.GeneratePassword();
    EXPECT(mask_str.length() == 6);
    // Check if correct chars are generated by mask
    EXPECT(std::islower(mask_str[0]));
    EXPECT(std::isupper(mask_str[1]));
    EXPECT(std::isdigit(mask_str[3]));
}

CASE("Check SetPasswordMask/Length correctness")
{
    PasswordGenParamsTest(lest_env);
}